export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_SET_ID = 'USER_SET_ID';
export const USER_LOGOUT = 'USER_LOGOUT';

export const USER_PROFILE_REQUEST = 'USER_PROFILE_REQUEST';
export const USER_PROFILE_RECEIVED = 'USER_PROFILE_RECEIVED';
export const USER_PROFILE_ERROR = 'USER_PROFILE_ERROR';

export const NAV_CHANGE_PAGE = 'NAV_CHANGE_PAGE';
export const NAV_TAB_CHANGE = 'NAV_TAB_CHANGE';
export const NAV_RESET_TAB = 'NAV_RESET_TAB';
export const SET_USER_TOKEN = 'SET_USER_TOKEN';

export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST';
export const USER_LOGIN_ERROR = 'USER_LOGIN_ERROR';

export const DASHBOARD_LOAD_POLICIES_REQUEST = 'DASHBOARD_LOAD_POLICIES_REQUEST';
export const DASHBOARD_LOAD_POLICIES_RECEIVED = 'DASHBOARD_LOAD_POLICIES_RECEIVED';
export const DASHBOARD_SELECT_POLICY = 'DASHBOARD_SELECT_POLICY';

export const DASHBOARD_LOAD_POLICY_ITEM_REQUEST = 'DASHBOARD_LOAD_POLICY_ITEM_REQUEST';
export const DASHBOARD_LOAD_POLICY_ITEM_RECEIVED = 'DASHBOARD_LOAD_POLICY_ITEM_RECEIVED';
export const DASHBOARD_SET_POLICIES_FIRST_PAGE = 'DASHBOARD_SET_POLICIES_FIRST_PAGE';
export const DASHBOARD_SELECT_CLIENT = 'DASHBOARD_SELECT_CLIENT';

export const GET_INSURANCE_CATEGORIES = 'GET_INSURANCE_CATEGORIES';
export const GET_INSURANCE_TYPES_REQUEST = 'GET_INSURANCE_TYPES_REQUEST';
export const GET_INSURANCE_TYPES_RECEIVED = 'GET_INSURANCE_TYPES_RECEIVED';

export const  GET_INSURANCE_VALUES = 'GET_INSURANCE_VALUES';

export const GET_INSURANCE_CATEGORIES_REQUEST = 'GET_INSURANCE_CATEGORIES_REQUEST';
export const GET_INSURANCE_CATEGORIES_RECEIVED = 'GET_INSURANCE_CATEGORIES_RECEIVED';

export const DASHBOARD_LOAD_CLIENT_REQUEST = 'DASHBOARD_LOAD_CLIENT_REQUEST';
export const DASHBOARD_LOAD_CLIENT_RECEIVED = 'DASHBOARD_LOAD_CLIENT_RECEIVED';
