export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_SET_ID = 'USER_SET_ID';
export const USER_LOGOUT = 'USER_LOGOUT';

export const USER_PROFILE_REQUEST = 'USER_PROFILE_REQUEST';
export const USER_PROFILE_RECEIVED = 'USER_PROFILE_RECEIVED';
export const USER_PROFILE_ERROR = 'USER_PROFILE_ERROR';

export const NAV_CHANGE_PAGE = 'NAV_CHANGE_PAGE';
export const NAV_TAB_CHANGE = 'NAV_TAB_CHANGE';
export const NAV_RESET_TAB = 'NAV_RESET_TAB';
export const SET_USER_TOKEN = 'SET_USER_TOKEN';

export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST';
export const USER_LOGIN_ERROR = 'USER_LOGIN_ERROR';

export const DASHBOARD_LOAD_POLICIES_REQUEST = 'DASHBOARD_LOAD_POLICIES_REQUEST';
export const DASHBOARD_LOAD_POLICIES_RECEIVED = 'DASHBOARD_LOAD_POLICIES_RECEIVED';
